export const products = [
  {
    '_id': '1',
    'name': 'Bakers Food',
    'image': '/static/images/food1.jpeg',
    'description':
      'Dog Food from Bakers Brand',
    'brand': 'Bakers',
    'category': 'Food',
    'price': 450.00,
    'countInStock': 50,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Bella Food',
    'image': '/static/images/food2.jpeg',
    'description':
      'Dog Food from Bella Brand',
    'brand': 'Bella',
    'category': 'Food',
    'price': 500.99,
    'countInStock': 25,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Freshpet Food',
    'image': '/static/images/food3.jpeg',
    'description':
      'Dog Food from Freshpet Brand',
    'brand': 'Freshpet',
    'category': 'Food',
    'price': 399.99,
    'countInStock': 50,
    'rating': 3.5,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'Pedigree Food',
    'image': '/static/images/food4.jpeg',
    'description':
      'Dog Food from Pedigree Brand',
    'brand': 'Pedigree',
    'category': 'Food',
    'price': 599.99,
    'countInStock': 30,
    'rating': 4.5,
    'numReviews': 12,
  },
	{
    '_id': '5',
    'name': 'Bakers Bed',
    'image': '/static/images/bed1.jpeg',
    'description':
      'Dog Bed from Bakers Brand',
    'brand': 'Bakers',
    'category': 'Bed',
    'price': 999.00,
    'countInStock': 10,
    'rating': 3,
    'numReviews': 22,
  },
  {
    '_id': '6',
    'name': 'Bella Bed',
    'image': '/static/images/bed2.jpeg',
    'description':
      'Dog Bed from Bella Brand',
    'brand': 'Bella',
    'category': 'Bed',
    'price': 1100.99,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 18,
  },
  {
    '_id': '7',
    'name': 'Freshpet Bed',
    'image': '/static/images/bed3.jpeg',
    'description':
      'Dog Bed from Freshpet Brand',
    'brand': 'Freshpet',
    'category': 'Bed',
    'price': 1300.99,
    'countInStock': 15,
    'rating': 4.5,
    'numReviews': 16,
  },
  {
    '_id': '8',
    'name': 'Pedigree Bed',
    'image': '/static/images/bed4.jpeg',
    'description':
      'Dog Bed from Pedigree Brand',
    'brand': 'Pedigree',
    'category': 'Bed',
    'price': 1950.99,
    'countInStock': 5,
    'rating': 4,
    'numReviews': 122,
  },

{
    '_id': '9',
    'name': 'Bakers Belt',
    'image': '/static/images/belt1.jpeg',
    'description':
      'Dog Belt from Bakers Brand',
    'brand': 'Bakers',
    'category': 'Belt',
    'price': 250.00,
    'countInStock': 10,
    'rating': 2.5,
    'numReviews': 2,
  },
  {
    '_id': '10',
    'name': 'Bella Belt',
    'image': '/static/images/belt2.jpeg',
    'description':
      'Dog Belt from Bella Brand',
    'brand': 'Bella',
    'category': ' Belt',
    'price': 199.99,
    'countInStock': 7,
    'rating': 4.5,
    'numReviews': 28,
  },
  {
    '_id': '11',
    'name': 'Freshpet Belt',
    'image': '/static/images/belt3.jpeg',
    'description':
      'Dog  Belt from Freshpet Brand',
    'brand': 'Freshpet',
    'category': 'Belt',
    'price': 230.99,
    'countInStock': 20,
    'rating': 4.5,
    'numReviews': 42,
  },
  {
    '_id': '12',
    'name': 'Pedigree Belt',
    'image': '/static/images/belt4.jpeg',
    'description':
      'Dog Belt from Pedigree Brand',
    'brand': 'Pedigree',
    'category': 'Belt',
    'price': 270.99,
    'countInStock': 12,
    'rating': 5.0,
    'numReviews': 10,
  },
	{
    '_id': '13',
    'name': 'Bakers Toy',
    'image': '/static/images/toy1.jpeg',
    'description':
      'Dog Toy from Bakers Brand',
    'brand': 'Bakers',
    'category': 'Toy',
    'price': 100.00,
    'countInStock': 10,
    'rating': 4.0,
    'numReviews': 12,
  },
  {
    '_id': '14',
    'name': 'Bella Toy',
    'image': '/static/images/toy2.jpeg',
    'description':
      'Dog Toy from Bella Brand',
    'brand': 'Bella',
    'category': 'Toy',
    'price': 110.99,
    'countInStock': 17,
    'rating': 4.5,
    'numReviews': 18,
  },
  {
    '_id': '15',
    'name': 'Freshpet Toy',
    'image': '/static/images/toy3.jpeg',
    'description':
      'Dog Toy from Freshpet Brand',
    'brand': 'Freshpet',
    'category': 'Toy',
    'price': 102.99,
    'countInStock': 51,
    'rating': 3.5,
    'numReviews': 12,
  },
  {
    '_id': '16',
    'name': 'Pedigree Toy',
    'image': '/static/images/toy4.jpeg',
    'description':
      'Dog Toy from Pedigree Brand',
    'brand': 'Pedigree',
    'category': 'Toy',
    'price': 130.45,
    'countInStock': 0,
    'rating': 5,
    'numReviews': 12,
  },
]


export default products