const products = [
  {
    '_id': '1',
    'name': 'Bakers Food',
    'image': '/images/food1.jpg',
    'description':
      'Dog Food from Bakers Brand',
    'brand': 'Bakers',
    'category': 'Food',
    'price': 10.00,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Bella Food',
    'image': '/images/food2.jpg',
    'description':
      'Dog Food from Bella Brand',
    'brand': 'Bella',
    'category': 'Food',
    'price': 11.99,
    'countInStock': 7,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Freshpet Food',
    'image': '/images/food3.jpg',
    'description':
      'Dog Food from Freshpet Brand',
    'brand': 'Freshpet',
    'category': 'Food',
    'price': 13.99,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'Pedigree Food',
    'image': '/images/food4.jpg',
    'description':
      'Dog Food from Pedigree Brand',
    'brand': 'Pedigree',
    'category': 'Food',
    'price': 19.99,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
	{
    '_id': '5',
    'name': 'Bakers Bed',
    'image': '/images/bed1.jpg',
    'description':
      'Dog Bed from Bakers Brand',
    'brand': 'Bakers',
    'category': 'Bed',
    'price': 10.00,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '6',
    'name': 'Bella Bed',
    'image': '/images/bed2.jpg',
    'description':
      'Dog Bed from Bella Brand',
    'brand': 'Bella',
    'category': 'Bed',
    'price': 11.99,
    'countInStock': 7,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '7',
    'name': 'Freshpet Bed',
    'image': '/images/bed3.jpg',
    'description':
      'Dog Bed from Freshpet Brand',
    'brand': 'Freshpet',
    'category': 'Bed',
    'price': 13.99,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': '8',
    'name': 'Pedigree Bed',
    'image': '/images/bed4.jpg',
    'description':
      'Dog Bed from Pedigree Brand',
    'brand': 'Pedigree',
    'category': 'Bed',
    'price': 19.99,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },

{
    '_id': '9',
    'name': 'Bakers Belt',
    'image': '/images/belt1.jpg',
    'description':
      'Dog Belt from Bakers Brand',
    'brand': 'Bakers',
    'category': 'Belt',
    'price': 5.00,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '10',
    'name': 'Bella Belt',
    'image': '/images/belt2.jpg',
    'description':
      'Dog Belt from Bella Brand',
    'brand': 'Bella',
    'category': ' Belt',
    'price': 4.99,
    'countInStock': 7,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '11',
    'name': 'Freshpet Belt',
    'image': '/images/belt3.jpg',
    'description':
      'Dog  Belt from Freshpet Brand',
    'brand': 'Freshpet',
    'category': 'Belt',
    'price': 3.99,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': '12',
    'name': 'Pedigree Belt',
    'image': '/images/belt4.jpg',
    'description':
      'Dog Belt from Pedigree Brand',
    'brand': 'Pedigree',
    'category': 'Belt',
    'price': 7.99,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
	{
    '_id': '13',
    'name': 'Bakers Toy',
    'image': '/images/toy1.jpg',
    'description':
      'Dog Toy from Bakers Brand',
    'brand': 'Bakers',
    'category': 'Toy',
    'price': 1.00,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '14',
    'name': 'Bella Toy',
    'image': '/images/toy2.jpg',
    'description':
      'Dog Toy from Bella Brand',
    'brand': 'Bella',
    'category': 'Toy',
    'price': 1.99,
    'countInStock': 7,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '15',
    'name': 'Freshpet Toy',
    'image': '/images/toy3.jpg',
    'description':
      'Dog Toy from Freshpet Brand',
    'brand': 'Freshpet',
    'category': 'Toy',
    'price': 2.99,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': '16',
    'name': 'Pedigree Toy',
    'image': '/images/toy4.jpg',
    'description':
      'Dog Toy from Pedigree Brand',
    'brand': 'Pedigree',
    'category': 'Toy',
    'price': 3.45,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
]


export default products